version: '2.2'

services:
  mean-dummy:
    image: mean-dummy
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
      - 48279:48279
    volumes:
      - .:/usr/local/bin/build
    ## set your startup file here