FROM node:8
ENV NODE_ENV production
ENV PORT 80
RUN ["mkdir", "-p", "/usr/local/bin/build"]
WORKDIR /usr/local/bin/build
COPY ["package.json", "package-lock.json", "./"]
RUN ["apt-get", "install", "build-essential", "-f", "-y", " --no-install-recommends"]
RUN npm install --global bunyan 
RUN ["echo", "Building for porduction..."]
EXPOSE 80 443
CMD ["npm", "run", "prepare:prod"]
COPY ./wwwroot .