base:
  port: 8080

paths:
  clientSrc: 'client'
  appFilesPaths: 
    - 'app.js'
    - 'db.js'
    - 'boot.js'
    - 'setup.js'
    - 'utils/**/*.js'
    - 'routes/**/*.js'
    - 'models/**/*.js'
    - 'middlewares/**/*.js'
  clientDist: 'client'
  appDist: 'server'
  testsSrc: 'tests/specs/**/*.spec.js'
  webpackFile: 'webpack.config.test.js'
  indexPath: 'client/index.html'

database:
  host: 'mongodb://test:test@ds048279.mlab.com:48279/event_man'
  creds:
    user: 'test'
    password: 'test'
